;; faltu --------------------------------------------------------------------------------
(defun files ()
  (interactive)
  (find-file "/mnt/localdisk_d/emacs-files/files.el"))
(defun goto ()
  (interactive)
  (find-file "/mnt/localdisk_d/emacs-files/faltu.sh"))
(defun advent ()
  (interactive)
  (find-file "/mnt/localdisk_d/__isi/faltu/advent/faltu.cpp"))



;; isi --------------------------------------------------------------------------------
(defun isi ()
  (interactive)
  (find-file "/mnt/localdisk_d/__isi/isi.org"))
(defun ant ()
  (interactive)
  (find-file "/mnt/localdisk_d/__isi/sem1/ant/faltu.org"))
(defun faltu ()
  (interactive)
  (find-file "/mnt/localdisk_d/__isi/faltu/faltu.py"))

;; tv ------------------------------------------------
(defun xfiles ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/xfiles/xfiles_s4/"))
(defun blacklist ()
  (interactive)
  (find-file "/home/user1/Documents/subtitles/blacklist/s08/"))
(defun watch ()
  (interactive)
  (find-file "/home/user1/Documents/subtitles/history.org"))


;; rougelike ------------------------------------------------------------------------------
(defun nethack ()
  (interactive)
  (find-file "/mnt/localdisk_d/linux-video-game/source/NetHack/src/dog.c"))

;; baje jinis --------------------------------------------------------------------------------
(defun gate ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/general/gate/gate2022/registration.org"))
(defun stat ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/theory/stat.org"))
(defun run ()
  (interactive)
  (let ((term-buffer (term "/bin/bash")))
    (set-buffer term-buffer)
    (term-send-raw-string "./run\n")
    ))
(defun exer ()
  (interactive)
  (find-file "~/exercism/emacs-lisp/hello-world/hello-world.el"))

;; faltu jinis ----------------------------------------------------------------------
(defun maze ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/curses/maze/maze.cpp"))
(defun engine ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/curses/engine/engine.cpp"))
(defun chip ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/emudev/chip8/emu/engine.c"))
(defun compiler ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/sem6/compiler/lockdown/code_generator/main.cpp"))
(defun dose ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/infocom/d-d-d.org"))
(defun infocom ()
  (interactive)
  ;;(find-file "/mnt/localdisk_d/__jadavpur/infocom/infocom"))
  (malyon "/mnt/localdisk_d/__jadavpur/infocom/infocom/HITCHHIK.z3"))
(defun mario ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/sem8/neat/mario.lua"))
(defun nintendo ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/hack/nitendo_hireme.c"))
(defun inf ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/sem7/information/run"))
(defun ai ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/sem7/ai/ai.org"))
(defun dm ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/curses/asadharon-dm/data.txt"))
(defun theory ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/theory/theory.org"))
(defun ascii ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/ascii.txt"))
(defun history ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/history.org"))
(defun comp ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/sem8/turing-complete/aaa.tex"))
(defun lisp ()
  (interactive)
  (find-file "/mnt/localdisk_d/__jadavpur/faltu/lisp.el"))
